spring:
  application:
    name: infuq-influxDB
  redis:
    host: 192.168.31.129
    port: 6379
    database: 2
    password: 9527
server:
  port: 56075

influx:
  url: http://192.168.10.25:8086
  token: 5Ze86MoaB1Xe38UGpJCYn_XrZ1vMjSFIlhDa--SPOWvtL9qT6V4cLOpHjEDYFAtg1kVozUkwNvfkQtalRjdLIw==
  org: foo
  bucket: user_data
